# Generated by Django 3.2.5 on 2021-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFileConverter', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('fileName', models.CharField(max_length=100)),
                ('originalFilePath', models.CharField(max_length=500)),
                ('convertedFilePath', models.CharField(max_length=500)),
                ('convertedFrom', models.CharField(max_length=20)),
                ('convertedTo', models.CharField(max_length=20)),
                ('requestedTime', models.DateTimeField()),
                ('conversionStatus', models.BooleanField()),
            ],
        ),
    ]
