# Generated by Django 3.2.5 on 2021-08-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFileConverter', '0003_fileconvert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileconvert',
            name='requestId',
        ),
    ]
